# Generated by Django 4.2 on 2025-10-17 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ejemplar', models.CharField(help_text='Código único para identificar este ejemplar específico', max_length=50, unique=True, verbose_name='Código de Ejemplar')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('mantenimiento', 'En Mantenimiento'), ('perdido', 'Perdido')], default='disponible', max_length=20, verbose_name='Estado')),
                ('fecha_adquisicion', models.DateField(auto_now_add=True, verbose_name='Fecha de Adquisición')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ejemplar',
                'verbose_name_plural': 'Ejemplares',
                'ordering': ['libro', 'codigo_ejemplar'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(help_text='Código ISBN único del libro (10 o 13 dígitos)', max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('año_publicacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(help_text='Documento Nacional de Identidad del socio', max_length=10, unique=True, verbose_name='DNI')),
                ('numero_socio', models.CharField(help_text='Número único asignado al socio', max_length=20, unique=True, verbose_name='Número de Socio')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el socio puede realizar préstamos', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Préstamo')),
                ('fecha_devolucion_prevista', models.DateField(help_text='Fecha límite para devolver el libro', verbose_name='Fecha de Devolución Prevista')),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre el préstamo o devolución', null=True)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='gestion_libros.ejemplar', verbose_name='Ejemplar')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='gestion_libros.socio', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('motivo', models.CharField(choices=[('retraso', 'Retraso en Devolución'), ('daño', 'Daño al Libro'), ('perdida', 'Pérdida del Libro'), ('otro', 'Otro Motivo')], max_length=20, verbose_name='Motivo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de la Multa')),
                ('pagada', models.BooleanField(default=False, verbose_name='Pagada')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('prestamo', models.ForeignKey(blank=True, help_text='Préstamo que originó la multa (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas', to='gestion_libros.prestamo', verbose_name='Préstamo Asociado')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='gestion_libros.socio', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='gestion_libros.libro', verbose_name='Libro'),
        ),
    ]
