# Generated by Django 4.2.16 on 2025-10-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplar',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el ejemplar está activo en el sistema (soft delete)', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='libro',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el libro está activo en el sistema (soft delete)', verbose_name='Activo'),
        ),
    ]
